### ISSUE TITLE
Binary jar file

### ISSUE THREAD

**Issue by kamilkosek** [octa22/org.openhab.binding.unifi#1]
Hi,
don´t know if it´s too soon to ask for a binary file, since the initial commit is 15 hours ago ;)
But I would appreciate it, because I don´t know how to build it and I would love to test it.
Maybe you need some help in testing and documenting this binding? 

Regards, 
Kamil

**Comment by octa22** [comment]
Hello,
plese do not expect too much. I'm just using the unifi AP to control the LED - on/off and blinking is currently possible (I can add more functionality later). But this binding functionality is limited to installed Unifi Controller software which exposes API - so it does not directly interacts with a Unifi AP since it has not public protocol. But if you want to test it you are welcome! I've added some documentation and will upload snapshot jar soon...

**Comment by octa22** [comment]
uploaded .jar snapshot

**Comment by kamilkosek** [comment]
Hi,
yeah, I know you need the controller software somewhere running because it is exposing the rest API.
I would like to contribute to this project, but I have no clue about Java programming nor binding creation for OpenHAB. My main goal would be, to be able to do some presence stuff with logged on devices. 
A nice to have feature: Enable/disable guest SSID´s and expose the (dynamic) passphrase  to OpenHAB so you could display it in HABPanel.

**Comment by octa22** [comment]
Hello, getting logged on devices is not a problem at all.  I can return list of currently logged on devices in some future version. Today I've implemented enabling/disabling WLAN network (including guest but no reading status at this time, just enable/disable). Unfortunately I do not know anything about dynamic passphrase feature, I have to simulate it first and expose then...I have updated doc and released a new beta version if you want to test you are welcome

**Comment by kamilkosek** [comment]
Hi,
I will test it ASAP, thanks :)
Do you know the php-api ? Just take a look [here](https://github.com/malle-pietje/Unifi-API-browser), it´s really well documentated and maybe you can find some useful stuff there.
For the dynamic passphrase feature I will open a new issue and descibe it.

**Comment by octa22** [comment]
Good morning,
I use php-api as one of the resources
I've added useful feature - displaying a Wifi password and generating +
setting a new password on demand.
Hope this is something you were looking for :-) I will release a brand new
snapshot soon...

Ondrej

2016-12-20 8:22 GMT+01:00 Kamil Kosek <notifications@github.com>:
